// Generated by CoffeeScript 1.11.1
(function() {
  var game_user;

  game_user = {
    count_step: 0,
    user_number: 0,
    numbers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    get_random: function(min, max) {
      return Math.round(Math.random() * (max - min) + min);
    },
    set_number: function() {
      this.user_number = parseInt(prompt('Загадайте число'));
      return this;
    },
    set_count_step: function() {
      this.count_step = this.get_random(1, 10);
      alert('Комньютер говорит что угадает за ' + this.count_step + ' шагов');
      return this;
    },
    try_number: function() {
      var computer_number, index, result;
      this.count_step--;
      if (this.count_step <= 0) {
        alert('Вы выиграли !!!');
        return;
      }
      index = this.get_random(0, this.numbers.length - 1);
      computer_number = this.numbers[index];
      if (computer_number === this.user_number) {
        alert('Компьютер выиграл !!!');
        return;
      }
      result = prompt('Компьютер говорит ' + computer_number);
      if (result === '>') {
        this.numbers = this.numbers.filter(function(v) {
          return v > computer_number;
        });
      } else {
        this.numbers = this.numbers.filter(function(v) {
          return v < computer_number;
        });
      }
      return this.try_number();
    }
  };

  game_user.set_number().set_count_step().try_number();

}).call(this);
